name: Sync Google Sheets Data

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Fetch Google Sheet as CSV
        uses: jakejarvis/google-sheets-to-csv@v2.0.1
        with:
          sheet_id: '1x5C-L1rMF94EdWPNZNzPHkxiENil8ZcOywiWAcVYjFQ'
          output: 'manual_prs.csv'
        env:
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}

      - name: Commit and Push
        run: |
          git config --global user.name "DataSyncBot"
          git config --global user.email "actions@github.com"
          git add manual_prs.csv
          git commit -m "Auto-update data via Service Account" || echo "No changes"
          git push
